\documentclass{article}

\begin{document}


\begin{table}[!htbp] \centering 
  \caption{Adjusted rand index } 
  \label{} 
\begin{tabular}{@{\extracolsep{5pt}} cccccccc} 
\\[-1.8ex]\hline 
\hline \\[-1.8ex] 
 & tSNEkmeans & SIMLR & SC3 & SNNCliq & pcaReduce & seurat & dbscan \\ 
\hline \\[-1.8ex] 
kumar2015 & 1 & 0.98 & 0.99 & 0.56 & 1 & 0.99 & 0.57 \\ 
trapnell2014 & 0.23 & 0.01 & 0.12 & 0 & 0.1 & 0.19 & 0.04 \\ 
xue2013 & 0.59 & 0.32 & 0.24 & 0.48 & 0.23 & 0 & 0 \\ 
koh2016 & 0.48 & 0.68 & 0.82 & 0 & 0.82 & 0.81 & 0.05 \\ 
\hline \\[-1.8ex] 
\end{tabular} 
\end{table} 


\end{document}